-- MySQL Script generated by MySQL Workbench
-- Fri Feb  2 22:32:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_facturacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_facturacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_facturacion` DEFAULT CHARACTER SET utf8 ;
USE `db_facturacion` ;

-- -----------------------------------------------------
-- Table `db_facturacion`.`tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_facturacion`.`tbl_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `nro_documento` VARCHAR(50) NOT NULL,
  `direccion` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_facturacion`.`tbl_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_facturacion`.`tbl_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `pre_unitario` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_facturacion`.`tbl_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_facturacion`.`tbl_factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nro_documento` VARCHAR(100) NOT NULL,
  `fec_emision` DATE NULL,
  `mto_subtotal` DOUBLE NULL,
  `mto_igv` DOUBLE NULL,
  `mto_total` DOUBLE NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_factura_tbl_cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_factura_tbl_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `db_facturacion`.`tbl_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_facturacion`.`tbl_factura_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_facturacion`.`tbl_factura_detalle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DOUBLE NOT NULL DEFAULT 0,
  `importe` DOUBLE NOT NULL,
  `factura_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_factura_detalle_tbl_factura1_idx` (`factura_id` ASC) VISIBLE,
  INDEX `fk_tbl_factura_detalle_tbl_producto1_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_factura_detalle_tbl_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `db_facturacion`.`tbl_factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_detalle_tbl_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `db_facturacion`.`tbl_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
