-- Active: 1706753740285@@127.0.0.1@3306@contactos
-- CREAR TABLAS 
CREATE TABLE contacto(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(200) NOT NULL
);

-- MODIFICAR TABLA 
ALTER TABLE contacto
ADD COLUMN pais VARCHAR(100) DEFAULT 'Perú';

-- ELIMINAR TABLA
DROP TABLE contacto