# Generated by Django 4.2 on 2024-03-09 02:37

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_foto', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('emp_tipo', models.CharField(choices=[('1', 'Administrador'), ('2', 'Cajero'), ('3', 'Mozo')], max_length=1)),
                ('usu_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_empleado',
            },
        ),
    ]
