# Generated by Django 4.2 on 2024-03-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='tbl_pedido',
        ),
        migrations.AlterModelTable(
            name='pedidodetalle',
            table='tbl_pedido_detalle',
        ),
    ]
