# Generated by Django 4.2 on 2024-03-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'PENDIENTE'), ('terminado', 'TERMINADO')], default='pendiente', max_length=20)),
            ],
        ),
    ]
